// ルートのbuild.gradleはこれだけでOK！
// リポジトリの設定（google()とか）はsettings.gradleに書いてあるから削除したよ
buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        // Android Gradle Pluginのバージョン
        classpath 'com.android.tools.build:gradle:8.1.1'
    }
}

plugins {
    id 'com.android.application' version '8.1.1' apply false
    id 'com.android.library' version '8.1.1' apply false
    id 'org.jetbrains.kotlin.android' version '1.8.10' apply false
}
